server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/study_room?charset=utf8&parseTime=True&loc=Local"
    debug: true

gfcli:
  gen:
    dao:
      - link:     "mysql:root:12345678@tcp(127.0.0.1:3306)/study_room"
        jsonCase: "Snake"



