// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDemo/internal/service/internal/dao/internal"
)

// internalSysConfigDataDao is internal type for wrapping internal DAO implements.
type internalSysConfigDataDao = *internal.SysConfigDataDao

// sysConfigDataDao is the data access object for table sys_config_data.
// You can define custom methods on it to extend its functionality as you wish.
type sysConfigDataDao struct {
	internalSysConfigDataDao
}

var (
	// SysConfigData is globally public accessible object for table sys_config_data operations.
	SysConfigData = sysConfigDataDao{
		internal.NewSysConfigDataDao(),
	}
)

// Fill with you ideas below.
