// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDemo/internal/service/internal/dao/internal"
)

// internalSysAdminDao is internal type for wrapping internal DAO implements.
type internalSysAdminDao = *internal.SysAdminDao

// sysAdminDao is the data access object for table sys_admin.
// You can define custom methods on it to extend its functionality as you wish.
type sysAdminDao struct {
	internalSysAdminDao
}

var (
	// SysAdmin is globally public accessible object for table sys_admin operations.
	SysAdmin = sysAdminDao{
		internal.NewSysAdminDao(),
	}
)

// Fill with you ideas below.
