// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure of table sys_menu for DAO operations like Where/Data.
type SysMenu struct {
	g.Meta     `orm:"table:sys_menu, do:true"`
	Id         interface{} // 主键ID
	Pid        interface{} // 父级ID
	Title      interface{} // 菜单标题
	Icon       interface{} // 图标
	Path       interface{} // 菜单路径
	Component  interface{} // 菜单组件
	Target     interface{} // 目标
	Permission interface{} // 权限标识
	ApiMethod  interface{} // GET/POST
	ApiPath    interface{} // Api 请求地址
	Type       interface{} // 类型：0菜单/1按钮
	Status     interface{} // 是否显示：0禁用/1正常
	Note       interface{} // 备注
	Sort       interface{} // 显示顺序
	CreatedBy  interface{} // 添加人
	CreatedAt  *gtime.Time // 创建时间
	UpdatedBy  interface{} // 更新人
	UpdatedAt  *gtime.Time // 更新时间
}
