// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure of table sys_config for DAO operations like Where/Data.
type SysConfig struct {
	g.Meta    `orm:"table:sys_config, do:true"`
	Id        interface{} // 主键ID
	Name      interface{} // 配置名称
	Code      interface{} // 配置编码
	Sort      interface{} // 排序
	Note      interface{} // 备注
	CreatedBy interface{} // 添加人
	CreatedAt *gtime.Time // 创建时间
	UpdatedBy interface{} // 更新人
	UpdatedAt *gtime.Time // 更新时间
}
