// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPartner is the golang structure of table sys_partner for DAO operations like Where/Data.
type SysPartner struct {
	g.Meta       `orm:"table:sys_partner, do:true"`
	Id           interface{} //
	PartnerNo    interface{} // 合伙人编号
	PartnerName  interface{} // 合伙人名称
	PartnerType  interface{} // 合伙人类型company,merchant
	ParentId     interface{} // 父级
	LinkMan      interface{} // 联系人
	LinkPhone    interface{} // 联系电话
	ContactPhone interface{} // 前台电话
	Province     interface{} // 省
	City         interface{} // 市
	County       interface{} // 县
	Address      interface{} // 地址
	Longitude    interface{} // 经度
	Latitude     interface{} // 纬度
	Note         interface{} // 备注
	CreatedAt    *gtime.Time // 创建时间
	CreatedBy    interface{} // 创建人
	UpdatedAt    *gtime.Time // 更新时间
	UpdatedBy    interface{} // 更新人
}
