// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysAdmin is the golang structure of table sys_admin for DAO operations like Where/Data.
type SysAdmin struct {
	g.Meta    `orm:"table:sys_admin, do:true"`
	Id        interface{} // 主键ID
	RoleId    interface{} // 角色ID
	Partners  interface{} //
	Nickname  interface{} // 昵称
	Avatar    interface{} // 头像
	Mobile    interface{} // 手机号码
	Account   interface{} //
	Password  interface{} // 登录密码
	Salt      interface{} // 盐加密
	Status    interface{} //
	Note      interface{} // 备注
	LoginNum  interface{} // 登录次数
	LoginIp   interface{} // 最近登录IP
	LoginTime *gtime.Time // 最近登录时间
	CreatedBy interface{} // 添加人
	CreatedAt *gtime.Time // 创建时间
	UpdatedBy interface{} // 更新人
	UpdatedAt *gtime.Time // 更新时间
}
