// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysRole is the golang structure of table sys_role for DAO operations like Where/Data.
type SysRole struct {
	g.Meta    `orm:"table:sys_role, do:true"`
	Id        interface{} //
	Name      interface{} //
	Code      interface{} // 角色编码
	Sort      interface{} //
	Note      interface{} // 备注
	CreatedAt *gtime.Time // 创建时间
	CreatedBy interface{} // 创建人
	UpdatedAt *gtime.Time // 更新时间
	UpdatedBy interface{} // 更新人
}
