// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDict is the golang structure of table sys_dict for DAO operations like Where/Data.
type SysDict struct {
	g.Meta    `orm:"table:sys_dict, do:true"`
	Id        interface{} // 主键
	Name      interface{} // 名称
	Code      interface{} // 编码
	Sort      interface{} // 排序
	Remark    interface{} // 备注
	Status    interface{} // 状态（字典 0正常 1停用 2删除）
	CreatedAt *gtime.Time // 创建时间
	CreatedBy interface{} // 创建人
	UpdatedAt *gtime.Time // 更新时间
	UpdatedBy interface{} // 更新人
}
