// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictData is the golang structure of table sys_dict_data for DAO operations like Where/Data.
type SysDictData struct {
	g.Meta    `orm:"table:sys_dict_data, do:true"`
	Id        interface{} // 主键
	DictId    interface{} // 字典类型id
	Value     interface{} // 值
	Code      interface{} // 编码
	Sort      interface{} // 排序
	Remark    interface{} // 备注
	IsWrite   interface{} // 是否填写1填写2不需要填
	Status    interface{} // 状态（字典 0正常 1停用 2删除）
	CreatedAt *gtime.Time // 创建时间
	CreatedBy interface{} // 创建人
	UpdatedAt *gtime.Time // 更新时间
	UpdatedBy interface{} // 更新人
}
