// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
	Id        uint64      `json:"id"         ` // 主键ID
	Name      string      `json:"name"       ` // 配置名称
	Code      string      `json:"code"       ` // 配置编码
	Sort      int         `json:"sort"       ` // 排序
	Note      string      `json:"note"       ` // 备注
	CreatedBy uint64      `json:"created_by" ` // 添加人
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	UpdatedBy uint64      `json:"updated_by" ` // 更新人
	UpdatedAt *gtime.Time `json:"updated_at" ` // 更新时间
}
