// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData struct {
	Id        uint64      `json:"id"         ` // 主键
	DictId    uint64      `json:"dict_id"    ` // 字典类型id
	Value     string      `json:"value"      ` // 值
	Code      string      `json:"code"       ` // 编码
	Sort      uint        `json:"sort"       ` // 排序
	Remark    string      `json:"remark"     ` // 备注
	IsWrite   uint        `json:"is_write"   ` // 是否填写1填写2不需要填
	Status    uint        `json:"status"     ` // 状态（字典 0正常 1停用 2删除）
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	CreatedBy uint64      `json:"created_by" ` // 创建人
	UpdatedAt *gtime.Time `json:"updated_at" ` // 更新时间
	UpdatedBy uint64      `json:"updated_by" ` // 更新人
}
