// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	Id        uint64      `json:"id"         ` // 主键
	OpenId    string      `json:"open_id"    ` //
	UnionId   string      `json:"union_id"   ` //
	Nickname  string      `json:"nickname"   ` // 昵称
	Phone     string      `json:"phone"      ` // 手机
	Avatar    string      `json:"avatar"     ` // 头像
	RealName  string      `json:"real_name"  ` //
	CreatedAt *gtime.Time `json:"created_at" ` // 创建时间
	CreatedBy uint64      `json:"created_by" ` // 创建人
	UpdatedAt *gtime.Time `json:"updated_at" ` // 更新时间
	UpdatedBy uint64      `json:"updated_by" ` // 更新人
}
