// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu struct {
	Id         uint64      `json:"id"         ` // 主键ID
	Pid        uint64      `json:"pid"        ` // 父级ID
	Title      string      `json:"title"      ` // 菜单标题
	Icon       string      `json:"icon"       ` // 图标
	Path       string      `json:"path"       ` // 菜单路径
	Component  string      `json:"component"  ` // 菜单组件
	Target     string      `json:"target"     ` // 目标
	Permission string      `json:"permission" ` // 权限标识
	ApiMethod  string      `json:"api_method" ` // GET/POST
	ApiPath    string      `json:"api_path"   ` // Api 请求地址
	Type       uint        `json:"type"       ` // 类型：0菜单/1按钮
	Status     uint        `json:"status"     ` // 是否显示：0禁用/1正常
	Note       string      `json:"note"       ` // 备注
	Sort       uint        `json:"sort"       ` // 显示顺序
	CreatedBy  uint64      `json:"created_by" ` // 添加人
	CreatedAt  *gtime.Time `json:"created_at" ` // 创建时间
	UpdatedBy  uint64      `json:"updated_by" ` // 更新人
	UpdatedAt  *gtime.Time `json:"updated_at" ` // 更新时间
}
