// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPartner is the golang structure for table sys_partner.
type SysPartner struct {
	Id           uint64      `json:"id"            ` //
	PartnerNo    string      `json:"partner_no"    ` // 合伙人编号
	PartnerName  string      `json:"partner_name"  ` // 合伙人名称
	PartnerType  string      `json:"partner_type"  ` // 合伙人类型company,merchant
	ParentId     uint64      `json:"parent_id"     ` // 父级
	LinkMan      string      `json:"link_man"      ` // 联系人
	LinkPhone    string      `json:"link_phone"    ` // 联系电话
	ContactPhone string      `json:"contact_phone" ` // 前台电话
	Province     string      `json:"province"      ` // 省
	City         string      `json:"city"          ` // 市
	County       string      `json:"county"        ` // 县
	Address      string      `json:"address"       ` // 地址
	Longitude    float64     `json:"longitude"     ` // 经度
	Latitude     float64     `json:"latitude"      ` // 纬度
	Note         string      `json:"note"          ` // 备注
	CreatedAt    *gtime.Time `json:"created_at"    ` // 创建时间
	CreatedBy    uint64      `json:"created_by"    ` // 创建人
	UpdatedAt    *gtime.Time `json:"updated_at"    ` // 更新时间
	UpdatedBy    uint64      `json:"updated_by"    ` // 更新人
}
