// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu struct {
	RoleId uint64 `json:"role_id" ` // 角色id
	MenuId uint64 `json:"menu_id" ` // 菜单id
}
