// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysPartnerDao is the data access object for table sys_partner.
type SysPartnerDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns SysPartnerColumns // columns contains all the column names of Table for convenient usage.
}

// SysPartnerColumns defines and stores column names for table sys_partner.
type SysPartnerColumns struct {
	Id           string //
	PartnerNo    string // 合伙人编号
	PartnerName  string // 合伙人名称
	PartnerType  string // 合伙人类型company,merchant
	ParentId     string // 父级
	LinkMan      string // 联系人
	LinkPhone    string // 联系电话
	ContactPhone string // 前台电话
	Province     string // 省
	City         string // 市
	County       string // 县
	Address      string // 地址
	Longitude    string // 经度
	Latitude     string // 纬度
	Note         string // 备注
	CreatedAt    string // 创建时间
	CreatedBy    string // 创建人
	UpdatedAt    string // 更新时间
	UpdatedBy    string // 更新人
}

//  sysPartnerColumns holds the columns for table sys_partner.
var sysPartnerColumns = SysPartnerColumns{
	Id:           "id",
	PartnerNo:    "partner_no",
	PartnerName:  "partner_name",
	PartnerType:  "partner_type",
	ParentId:     "parent_id",
	LinkMan:      "link_man",
	LinkPhone:    "link_phone",
	ContactPhone: "contact_phone",
	Province:     "province",
	City:         "city",
	County:       "county",
	Address:      "address",
	Longitude:    "longitude",
	Latitude:     "latitude",
	Note:         "note",
	CreatedAt:    "created_at",
	CreatedBy:    "created_by",
	UpdatedAt:    "updated_at",
	UpdatedBy:    "updated_by",
}

// NewSysPartnerDao creates and returns a new DAO object for table data access.
func NewSysPartnerDao() *SysPartnerDao {
	return &SysPartnerDao{
		group:   "default",
		table:   "sys_partner",
		columns: sysPartnerColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysPartnerDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysPartnerDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysPartnerDao) Columns() SysPartnerColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysPartnerDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysPartnerDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysPartnerDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
