// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysAdminDao is the data access object for table sys_admin.
type SysAdminDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns SysAdminColumns // columns contains all the column names of Table for convenient usage.
}

// SysAdminColumns defines and stores column names for table sys_admin.
type SysAdminColumns struct {
	Id        string // 主键ID
	RoleId    string // 角色ID
	Partners  string //
	Nickname  string // 昵称
	Avatar    string // 头像
	Mobile    string // 手机号码
	Account   string //
	Password  string // 登录密码
	Salt      string // 盐加密
	Status    string //
	Note      string // 备注
	LoginNum  string // 登录次数
	LoginIp   string // 最近登录IP
	LoginTime string // 最近登录时间
	CreatedBy string // 添加人
	CreatedAt string // 创建时间
	UpdatedBy string // 更新人
	UpdatedAt string // 更新时间
}

//  sysAdminColumns holds the columns for table sys_admin.
var sysAdminColumns = SysAdminColumns{
	Id:        "id",
	RoleId:    "role_id",
	Partners:  "partners",
	Nickname:  "nickname",
	Avatar:    "avatar",
	Mobile:    "mobile",
	Account:   "account",
	Password:  "password",
	Salt:      "salt",
	Status:    "status",
	Note:      "note",
	LoginNum:  "login_num",
	LoginIp:   "login_ip",
	LoginTime: "login_time",
	CreatedBy: "created_by",
	CreatedAt: "created_at",
	UpdatedBy: "updated_by",
	UpdatedAt: "updated_at",
}

// NewSysAdminDao creates and returns a new DAO object for table data access.
func NewSysAdminDao() *SysAdminDao {
	return &SysAdminDao{
		group:   "default",
		table:   "sys_admin",
		columns: sysAdminColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysAdminDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysAdminDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysAdminDao) Columns() SysAdminColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysAdminDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysAdminDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysAdminDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
